### ISSUE TITLE
Sensibo keeps hanging up homebridge

### ISSUE THREAD

**Issue by leoneleone** [pdlove/homebridge-sensibo#4]
I keep getting this error in homebridge with my pods.

Is this a error handling issue? 

error at req:  { [Error: connect ECONNREFUSED 54.77.241.118:443]
  code: 'ECONNREFUSED',
  errno: 'ECONNREFUSED',
  syscall: 'connect',
  address: '54.77.241.118',
  port: 443 }

**Comment by pdlove** [comment]
That is partially an error handling issue. The core problem is that the Sensibo servers can't handle very many requests before they flake out and I don't have the expertise to get the data synchronously.
This hasn't been an issue for any other plugin I've worked with because other APIs have a way to fetch all data for all devices with a single call.
How many pods do you have? I know I've got this working with ok stability with 3 pods.

**Comment by leoneleone** [comment]
Any chance we can get the guys at Sensibo to help us out?
I can send them links to the plugin. They would know more

**Comment by leoneleone** [comment]
I've got 3pods too

Btw, I've changed a few lines of code in the pods.js to integrate all characteristics under just the Thermostat.Service
I can now turn the pods on/off, "fan" mode can be turned on using HomeKit thermostat mode AUTO, added rotation speed to thermostat.service as well. All works great

**Comment by pdlove** [comment]
Sounds good. Feel free to fork and submit a pull request. I've got a few ideas to work around the not responding error.

**Comment by payote** [comment]
@leoneleone Would love to try your changes as well. I'm using the pods more for "reporting" temp and humidity now. Ended up getting a second Harmony hub so I can use all the commands on my various fans/heaters/ac units.

**Comment by leoneleone** [comment]
@pdlove - I've sent you a "file change proposal" for pods.js to modify Characteristic.On + Characteristic.RotationSpeed
Didn't want to submit a pull request as my fork has some setting edits which suit my particular Sensibo setup and AC units, they might not be ideal for everyone else.

**Comment by leoneleone** [comment]
@payote - You will need to edit your pods.js file. Replace the original code from Line136 to Line171 with code you see here:
	this.getService(Service.Thermostat)
		.addCharacteristic(Characteristic.On)
		.on('get', function(callback) {
			if (that.state.on=true)
				callback(null, true);
			else if (that.state.on=false)
				callback(null, false); 	
		})
		.on('set', function(value, callback) {
			callback();
			if (value) {
				that.state.on=true;
			} else {
				that.state.on=false;
			}
			that.platform.api.submitState(that.deviceid, that.state);
		})

	this.getService(Service.Thermostat)
		.addCharacteristic(Characteristic.RotationSpeed)
		.on('get', function(callback) {
			switch (that.state.fanLevel) {
				case 'low':
					callback(null,25);
					break;
				case 'medium':
					callback(null,50);
					break;
				case 'high':
					callback(null,100);
					break;
				case 'auto':
					callback(null,0);
					break;
			}
		})

Let me know how that works out for you 😊

**Comment by payote** [comment]
Great, thanks for figuring this out and for the PR.

**Comment by leoneleone** [comment]
@payote 
By the way, I still can't change the fan rotation speed using Siri commands. Works fine via a HomeKit app, but Siri voice commands for rotation speed just don't register. 

Were you able to use voice commands to change the fan rotation speed using the original pods.js file?
If so, then only change the first section of code mentioned above. The one related to Characteristic.On
Leave the rest as is.

Please let me know and I'll adjust the pull request accordingly.

**Comment by payote** [comment]
@leoneleone 

No I was unable to control fan speed - either with Siri or with HomeKit apps.

**Comment by payote** [comment]
I won't be able to implement/test your code changes until I get home later tonight (approximately 12+ hours from now).

**Comment by leoneleone** [comment]
@payote - Great. Let me know how it workspace you've tested. 

Turning the Sensibo units On/Off via direct PowerState commands works much better in my opinion.

Perhaps Rotation Speed voice commands are buggy in HomeKit/iOS9..? I don't understand why it works via an app but not Siri.

**Comment by payote** [comment]
I think Rotation supports increments - Not all fans have a low/med/high state. So I believe I read that the Sensibo API supports an increment value. Maybe Siri is expecting to hear a percentage or increment?

**Comment by payote** [comment]
@leoneleone Sorry had a looooooong day/night at work yesterday. I've edited the pods.js file but haven't subbed it in yet and won't be able to test it until I get home tonight. Apologies for the delay.

**Comment by payote** [comment]
I'm having some kind of server issues with Sensibo. The pods are discovered but not connecting to the Sensibo server (this happens with your code AND with pdlove's original pods.js code). I haven't had time to track down what's going on, hope to get on that this weekend.

**Comment by leoneleone** [comment]
That was happening to me too. What does error readout say? Something like connection refused by the Sensibo server. I contacted Sensibo about this via Facebook and they confirmed they were having server issues. I just let Homebridge run on my PI and things got more stable with time. 

Maybe contact Sensibo explaining the issue and quote the error readout too. Mine has been running stable for days now. 

I also know how to fix the FanLevel/RotationSpeed issue. 

I'll let you know more soon.

**Comment by leoneleone** [comment]
@payote @pdlove 
The issues we are having with RotationSpeed not working properly are due Value Format mismatch.
Sensibo is expecting/reporting STRING values for (temp_temperature, mode, fanLevel) while HomeKit is expecting/sending FLOAT values for (CurrentTemperature, RotationSpeed), and UINT8 values for (Current/TargetHeatingCoolingState).
HomeKit seems to doing some format conversion when its GETting characteristics, but Sensibo server is not converting formats SET to it. 
This is also the case with some HomeKit apps, I believe they handle conversion of formats within their app, but all are doing the conversion differently. It would be better to SET characteristics in the format the Sensibo server is expecting them. 

Can we convert between the two values formats in the code somehow? Binding these Characteristics/Properties might be a better approach perhaps?

I want to add a BatteryLevel Characteristic as well, which HomeKit/HAP-NodeJS already support. Please look at [https://github.com/KhaosT/HAP-NodeJS/blob/master/lib/gen/HomeKitTypes.js](url), but I can't see any references to Battery Level in the Sensibo API. I'm pretty sure there will be a format mismatch between HomeKit's and Sensibo's values for this.

**Comment by pdlove** [comment]
@leoneleone Are you only seeing the temperature problem when setting the temperature?
JSON is highly datatype agnostic so I have a hard time understanding how you could have the conversion issues.
I did follow their python example for how to set it.
Also, I didn't see battery level in the api. I've used it before several times in other plugins.

**Comment by leoneleone** [comment]
@pdlove - 
Sensibo battery level from the API -

https://home.sensibo.com/api/v2/pods/podid/measurements?fields=batteryVoltage,temperature,humidity,time&apiKey=apikey

hope that helps :)

**Comment by pdlove** [comment]
That helps a bit. can you post what a battery Voltage looks like?
I need to know if it is 0-1, 0-100, or the actual voltage of the battery. If it is the actual voltage of the battery, let me know what kind and how many batteries it takes.
Just a minor issue with not actually owning a device I'm developing for. :)

**Comment by leoneleone** [comment]
It's voltage in mV (so 2950 is 2.95V).
This is the datasheet for the battery: http://data.energizer.com/PDFs/123.pdf

To know the decline in voltage is not a straight forward matter. The pod should keep on working to about 2800, and it will keep on transmitting temperature and humidity to 2400 even.

**Comment by pdlove** [comment]
We'll start it by calling 2600 empty and I'll see what I can do to fit the curve to get a fairly accurate percentage. I'll work this out on Sunday.

**Comment by leoneleone** [comment]
@pdlove - Great! 
I've noticed some minor typos/errors in the pods.js file. I'm clearing them up now.

Also, seeing as you're adding Battery measurement, perhaps its better to change "refreshTemperature" function to be called "refreshMeasurements" and for it to include ('current' temperature, humidity, battery)? seems more logical.

**Comment by leoneleone** [comment]
@pdlove - 
When using an app to change RotationSpeed (I use the Elgato Eve app), the ui presents you with a slider to set the fan speed from 0%-100, but moving the slider is buggy and keeps jumping between the numerical values. 
Could this be due to the RotationSpeed characteristic being a floating point rather that a pure integer? If so, can it be fixed somehow?
Regarding Siri Command control of RotationSpeed, I'm now thinking that Apple hasn't added that functionality to Siri yet.

Setting TargetHeatingCooling using Siri Commands:
"Heat the (Room/Thermostat) to X degrees", "Cool the (Room/Thermostat) to X degrees" both work as expected.

[forums](http://www.smarthomehub.net/forums/discussion/544/official-ecobee3-homekit-feedback-thread) 
A user has tested Siri Commands with his officially HKcompatible ecobee3 thermostat:

**To resume your thermostat schedule, say, “Siri, enable [ecobee3 name] Resume Schedule.”**

So perhaps that "Resume Schedule" Siri Command is linked to TargetHeatingCooling.AUTO
I'll test this and let you know.

**Comment by pdlove** [comment]
@leoneleone The problem you're experiencing on rotational speed is because the app is sending many API requests and Sensible isn't reacting to them in order. This could potentially be resolved by waiting two seconds after the first command to send the command to the api. I have been considering doing this on one of my other plugins as well to reduce spasticness.

**Comment by bgottsch** [comment]
Hi, @leoneleone @pdlove @payote 
I've been reading this discussion and had time to modify the original project to implement certain features described here and make some changes to the way the accessory is configured, by deleting the fan service and adding characteristics to the thermostat. I still don't know about Siri support, but I'm currently working on making it work. I'll notify of any progress on the pull thread.

[Pull request](https://github.com/pdlove/homebridge-sensibo/pull/14)

Regards,
Beno

**Comment by ChiffaN** [comment]
Have these additions been merged into the 0.0.1 version? They look like very promising, but it seems some changes have been made to pods.js as the line numbers do not match. Also, is it possible to show humidity on the badge as well? or maybe split it as a separate tile or something?

**Comment by ChiffaN** [comment]
Using npm install -g homebridge-sensibo i am getting 0.0.1 for some reason

Best regards,
Oleg Neyolov

**Comment by leoneleone** [comment]
npm install -g git+https://github.com/pdlove/homebridge-sensib

**Comment by pdlove** [comment]
npm has been updated with the latest version of homebridge.
